### ISSUE TITLE
Unload from report to s3

### ISSUE THREAD

**Issue by bradanton** [SoftwareCountry/CDMSouffleur#1]
Data format:
without columns
DELIMITER AS '\t
GZIP
+
metada:
dx1,dx2,dx3,dx4,dx5,proc1,enrolid,procgrp,stdplac,stdprov,tsvcdat,svcdate,copay,coins,deduct,netpay,cob,pay,revcode,claim_type,provid,fachdid,year,provideridkey,seqnum,priority,currencyconceptid,procmod,dxver,proctyp,vendor

**Comment by alexanderlopoukhov** [comment]
NB!!!
metadata folder contans {table_name}.txt with comma separeted header
